// Generated by src/seed/upload-dish-photos.ts: SKU → photo uploaded to Vercel Blob, with credit.
export const DISH_PHOTOS: Record<string, { url: string; credit: string }> = {
  'BWL-PTK-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/bwl-ptk-01.webp',
    credit: 'Photo by Kalyani Akella on Unsplash (https://unsplash.com/photos/vgTntT8PmIM)',
  },
  'BWL-BYO-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/bwl-byo-01.webp',
    credit:
      'Photo by Zayed Ahmed Zadu on Unsplash (https://unsplash.com/photos/spicy-chicken-and-rice-bowl-with-cucumber-and-onion-KnIeqQyEi2E)',
  },
  'BWL-RJC-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/bwl-rjc-01.webp',
    credit:
      'Photo by PRATEEK JAISWAL on Unsplash (https://unsplash.com/photos/a-white-plate-topped-with-rice-and-beans-93RhzdPTCyU)',
  },
  'PLT-CHL-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/plt-chl-01.webp',
    credit:
      'Photo by Zoshua Colah on Unsplash (https://unsplash.com/photos/chana-masala-with-fried-bhatura-bread-Idh9dnG2v8w)',
  },
  'PLT-BCH-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/plt-bch-01.webp',
    credit: 'Photo by Imad 786 on Unsplash (https://unsplash.com/photos/gwUA_pHaOYY)',
  },
  'PLT-DLM-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/plt-dlm-01.webp',
    credit:
      'Photo by Chetanya Sharma on Unsplash (https://unsplash.com/photos/dal-makhani-in-black-pot-WR13Tw8gmsA)',
  },
  'PLT-PLK-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/plt-plk-01.webp',
    credit:
      'Photo by Chetanya Sharma on Unsplash (https://unsplash.com/photos/a-delicious-indian-meal-with-spinach-and-flatbread-_bAW_ln_-Zs)',
  },
  'THL-JAN-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/thl-jan-01.webp',
    credit:
      'Photo by Barun Ghosh on Unsplash (https://unsplash.com/photos/assorted-foods-on-stainless-steel-tray-wClFKcjhNcI)',
  },
  'BIR-VEG-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/bir-veg-01.webp',
    credit: 'Photo by Nosh Caterers on Unsplash (https://unsplash.com/photos/L07CScWpHhk)',
  },
  'BIR-CHK-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/bir-chk-01.webp',
    credit: 'Photo by Sarabjeet Singh on Unsplash (https://unsplash.com/photos/q29oNjt3sEQ)',
  },
  'WRP-PNR-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/wrp-pnr-01.webp',
    credit:
      'Photo by Ryan Concepcion on Unsplash (https://unsplash.com/photos/wrapped-food-with-gravies-50KffXbjIOg)',
  },
  'WRP-CHK-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/wrp-chk-01.webp',
    credit:
      'Photo by Max Griss on Unsplash (https://unsplash.com/photos/white-and-brown-food-on-white-ceramic-plate-Spp1G283dow)',
  },
  'SAL-QCP-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/sal-qcp-01.webp',
    credit:
      'Photo by Sonny Mauricio on Unsplash (https://unsplash.com/photos/a-blue-bowl-filled-with-vegetables-and-a-wooden-spoon-yhc4pSbl01A)',
  },
  'SAL-SPR-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/sal-spr-01.webp',
    credit: 'Photo by Sumeet B on Unsplash',
  },
  'BRK-DSA-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/brk-dsa-01.webp',
    credit:
      'Photo by Deepal Tamang on Unsplash (https://unsplash.com/photos/dosa-with-masala-and-chutney-breakfast-5oF7d_hPJG4)',
  },
  'BRK-PHA-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/brk-pha-01.webp',
    credit:
      'Photo by Zoshua Colah on Unsplash (https://unsplash.com/photos/poha-breakfast-with-peanuts-and-lime-_yxndM0wO8c)',
  },
  'BRK-APR-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/brk-apr-01.webp',
    credit:
      'Photo by Rimsha Noor on Unsplash (https://unsplash.com/photos/a-plate-of-flat-bread-on-a-wooden-table-uOcFC1NH5h0)',
  },
  'SNK-SMS-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/snk-sms-01.webp',
    credit:
      'Photo by kabir cheema on Unsplash (https://unsplash.com/photos/samosas-with-green-chili-and-pomegranate-8T9AVksyt7s)',
  },
  'DES-GLB-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/des-glb-01.webp',
    credit:
      'Photo by Muhammad talha on Unsplash (https://unsplash.com/photos/brown-round-fruits-on-clear-glass-bowl-wJ818PxbMy0)',
  },
  'DES-PHR-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/des-phr-01.webp',
    credit:
      'Photo by Aneta Voborilova on Unsplash (https://unsplash.com/photos/a-bowl-of-mango-soup-next-to-a-glass-of-milk-BFQMn0-MEao)',
  },
  'DRK-LSI-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/drk-lsi-01.webp',
    credit:
      'Photo by Ellie Ellien on Unsplash (https://unsplash.com/photos/white-liquid-in-clear-drinking-glass-D0DY3mA3T7Q)',
  },
  'DRK-LIM-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/drk-lim-01.webp',
    credit:
      'Photo by Rajasekhar R on Unsplash (https://unsplash.com/photos/a-glass-of-lemonade-with-limes-and-limes-U4mCZiti-aM)',
  },
  'DSH-SAG-01': {
    url: 'https://9kesdfburfhfywbu.public.blob.vercel-storage.com/seed/dishes/dsh-sag-01.webp',
    credit: 'Photo by You Le on Unsplash',
  },
};
