import { existsSync, writeFileSync } from 'node:fs';
import { put } from '@vercel/blob';
import { DISH_PHOTO_SOURCES } from './dish-photo-sources.js';

/**
 * One-off: copies the chosen free-licence (Unsplash) photos into our Vercel Blob store, resized to
 * 900×675 WebP, and writes src/seed/dish-photos.ts (SKU → Blob URL + credit) for the seed to use.
 * Re-running overwrites the same Blob paths, so URLs stay stable.
 *
 *   pnpm --filter @fernleaf/api build && node apps/api/dist/seed/upload-dish-photos.js   (from apps/api)
 */
async function main() {
  if (existsSync('.env')) process.loadEnvFile('.env');
  if (!process.env.BLOB_READ_WRITE_TOKEN) throw new Error('BLOB_READ_WRITE_TOKEN is not set');

  const result: Record<string, { url: string; credit: string }> = {};
  for (const source of DISH_PHOTO_SOURCES) {
    // Unsplash's image CDN resizes and converts on request.
    const response = await fetch(`${source.imageUrl}?w=900&h=675&fit=crop&fm=webp&q=75`);
    if (!response.ok) throw new Error(`${source.sku}: download failed (${response.status})`);
    const body = Buffer.from(await response.arrayBuffer());

    const blob = await put(`seed/dishes/${source.sku.toLowerCase()}.webp`, body, {
      access: 'public',
      contentType: 'image/webp',
      addRandomSuffix: false,
      allowOverwrite: true,
    });
    result[source.sku] = {
      url: blob.url,
      credit: source.photographer
        ? `Photo by ${source.photographer} on Unsplash${source.pageUrl ? ` (${source.pageUrl})` : ''}`
        : `Photo from Unsplash${source.pageUrl ? ` (${source.pageUrl})` : ''}`,
    };
    console.log(`${source.sku}: ${Math.round(body.length / 1024)} KB → ${blob.url}`);
  }

  const lines = Object.entries(result).map(
    ([sku, photo]) => `  ${JSON.stringify(sku)}: ${JSON.stringify(photo)},`,
  );
  writeFileSync(
    'src/seed/dish-photos.ts',
    `// Generated by src/seed/upload-dish-photos.ts: SKU → photo uploaded to Vercel Blob, with credit.\nexport const DISH_PHOTOS: Record<string, { url: string; credit: string }> = {\n${lines.join('\n')}\n};\n`,
  );
  console.log(`Uploaded ${Object.keys(result).length} photos; wrote src/seed/dish-photos.ts`);
}

await main();
